apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.fullname" . }}
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgres.external.enabled }}
  externalPostgresUri: {{ .Values.postgres.external.uri | b64enc }}
  {{- end }}
  {{- if .Values.configuration.authentication.authSecret }}
  authSecret: {{ .Values.configuration.authentication.authSecret | b64enc }}
  {{- end }}
